# Generated by Django 4.0.4 on 2022-04-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('webhook_url', models.CharField(max_length=60)),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Running'), (2, 'Paused'), (3, 'Finished')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
